# Generated by Django 5.2.11 on 2026-03-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='coach_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
