# Generated by Django 5.2.11 on 2026-03-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_coach_coach_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='coach_code',
        ),
    ]
